[package]
name = "vunk-parser"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true

chumsky = "1.0.0-alpha.4"

vunk-lexer = { path = "../vunk-lexer" }

